"""Restore an archive produced by scripts/export.py back into this repository.

The export wraps everything in a `<experiment>/` directory and rewrites the game steps for the
website, so a plain `tar xzf` no longer lands in `results/benchmarks/`. This script strips the
wrapper, converts the steps back to the package schema and writes the files where the trackers
expect them, overwriting only the matchups/games contained in the archive.

Examples:
    uv run python scripts/import.py qwen_ttt.tar.gz
    uv run python scripts/import.py qwen_*.tar.gz --dry-run
    uv run python scripts/import.py qwen_ttt.tar.gz --with-analysis --with-experiment
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _website_import import restore_archive  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("archives", nargs="+", help="exported .tar.gz archive(s)")
    parser.add_argument("--dest", default=".", help="repository root to restore into (default: cwd)")
    parser.add_argument("--with-analysis", action="store_true", help="also restore analysis/benchmarks/ (derived, normally regenerated by analyze.py)")
    parser.add_argument("--with-experiment", action="store_true", help="also write experiments/benchmarks/<name>.json (overwrites the local experiment definition)")
    parser.add_argument("--dry-run", action="store_true", help="report what would be written without touching the filesystem")
    args = parser.parse_args()

    dest = Path(args.dest)
    for archive in args.archives:
        counts = restore_archive(archive, dest, with_analysis=args.with_analysis, with_experiment=args.with_experiment, dry_run=args.dry_run)
        prefix = "would restore" if args.dry_run else "restored"
        experiments = ", ".join(sorted(counts.experiments)) or "-"
        stats = f", {counts.game_stats} game-stat files" if args.with_analysis else ""
        print(f"{prefix} {archive} -> {experiments}: {counts.matchups} matchups, {counts.games} games{stats} ({counts.overwritten} existing files overwritten)")


if __name__ == "__main__":
    main()
